modLoader="javafml"
loaderVersion="[21.1.10,)"
license="MIT"

[[mods]]
modId="edgemod"
version="1.0.0"
displayName="Edge PvP Mod"
authors="Yunus Emin"
description="Emildian Edge Studios Özel PvP Botu"
