modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
    modId="edgemod"
    version="1.0.0"
    displayName="Edge PvP Mod"
    displayTest="MATCH_VERSION"
    authors="Yunus Emin"
    description="Emildian Edge Studios tarafindan gelistirilen PvP Bot Modu."

[[dependencies.edgemod]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.10,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.edgemod]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,)"
    ordering="NONE"
    side="BOTH"
